name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self2.yml
jobs:
  self-hosted-number2:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v2
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir npm-cli
           cd npm-cli
           git clone https://github.com/npm/cli.git
       
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm version
       
       - uses: actions/github-script@v5
         id: my-script
         with:
           result-encoding: string
           script: return "I will be string (not JSON) encoded!"
